name: build and push

on:
  push:
    branches:
      - main


jobs:
  buil-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{  secrets.DOCKERHUB_PASSWORD }}
          docker build -t iagomauricio/app-task:latest .
          docker push iagomauricio/app-task:latest
